# Generated by Django 4.2.3 on 2024-05-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0027_product_delevery_country_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='postal_code',
            field=models.PositiveIntegerField(),
        ),
    ]
