# Generated by Django 4.2.3 on 2024-05-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0028_alter_delivery_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='phone_number',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='is_default',
        ),
    ]
