# Generated by Django 4.2.3 on 2024-05-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0030_order_order_approve_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
