# Generated by Django 4.2.3 on 2024-05-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0032_order_created_at_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.TextField(default=None),
        ),
    ]
