# Generated by Django 4.2.3 on 2024-05-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0035_remove_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.TextField(blank=True, default='001', null=True),
        ),
    ]
