# Generated by Django 4.2.3 on 2024-05-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0037_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='deli',
            field=models.ForeignKey(default=344, on_delete=django.db.models.deletion.CASCADE, to='a1.delivery'),
            preserve_default=False,
        ),
    ]
